"""Shared, deliberately broad crawl limits for Clue's local job discovery."""

ROBOTS_TXT_OBEY = False
SCRAPLING_CONCURRENT_REQUESTS = 8
SCRAPLING_CONCURRENT_REQUESTS_PER_DOMAIN = 2
SCRAPLING_DOWNLOAD_DELAY_SECONDS = 1.0

FAST_FEED_REFRESH_SECONDS = 3_600
PUBLIC_CRAWL_REFRESH_SECONDS = 21_600
SOURCE_ERROR_RETRY_SECONDS = 300
QUERY_ERROR_RETRY_SECONDS = 300
TRANSIENT_COMPANY_ERROR_STATES = frozenset({"api_error", "dynamic_unavailable"})

COMPANY_HTML_PAGE_LIMIT = 25
COMPANY_CHILD_SITEMAP_LIMIT = 10
COMPANY_SITEMAP_JOB_PAGE_LIMIT = 50
COMPANY_DYNAMIC_RENDER_LIMIT = 20
STANDALONE_CAREER_PAGE_LIMIT = 100

JUSTREMOTE_PAGE_LIMIT = 200
JUSTREMOTE_LISTING_PAGE_LIMIT = 80
JUSTREMOTE_JOB_PAGE_LIMIT = 120
JUSTREMOTE_RESULT_PAGE_LIMIT = 20
